package tnp

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestCommon(t *testing.T) {
	is := assert.New(t)

	info := Parse("Wuthering Heights E01-E02 2009 1080p Blu-ray x265 AC3￡cXcY@FRDS", false)
	is.NotNil(info)
	is.Equal(info.Name, "Wuthering Heights")
	is.Equal(info.Episode, []int{1, 2})
	is.Equal(info.Year, "2009")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "x265")
	is.Equal(info.Audio, "AC3")
	is.Equal(info.Producer, "￡cXcY@FRDS")

	info = Parse("Wuthering Heights E01-E02 2009 1080p Blu-ray x265 AC3￡cXcY@FRDS", true)
	is.NotNil(info)
	is.Equal(info.Name, "Wuthering Heights")
	is.Equal(info.Episode, []int{1, 2})
	is.Equal(info.Year, "2009")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "H.265")
	is.Equal(info.Audio, "Dolby Digital")
	is.Equal(info.Producer, "￡cXcY@FRDS")

	info = Parse("The Walking Dead Complete S01-S11 2010-2021 1080p Blu-ray x265 AC3￡cXcY@FRDS", false)
	is.Equal(info.Name, "The Walking Dead")
	is.Equal(info.Season, []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11})
	is.Equal(info.Year, "2010-2021")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "x265")
	is.Equal(info.Audio, "AC3")
	is.Equal(info.Producer, "￡cXcY@FRDS")
	is.Equal(info.MediaType, TypeTVSeries)

	info = Parse("The Walking Dead Complete S01-S11 2010-2021 1080p Blu-ray x265 AC3￡cXcY@FRDS", true)
	is.Equal(info.Name, "The Walking Dead")
	is.Equal(info.Season, []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11})
	is.Equal(info.Year, "2010-2021")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "H.265")
	is.Equal(info.Audio, "Dolby Digital")
	is.Equal(info.Producer, "￡cXcY@FRDS")
	is.Equal(info.MediaType, TypeTVSeries)

	info = Parse("21 2008 1080p CEE Blu-ray AVC TrueHD 5.1-HDMaN", false)
	is.Equal(info.Name, "21")
	is.Equal(info.Year, "2008")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "AVC")
	is.Equal(info.Audio, "TrueHD 5.1")
	is.Equal(info.Producer, "HDMaN")
	is.Equal(info.MediaType, TypeMovie)

	info = Parse("21 2008 1080p CEE Blu-ray AVC TrueHD 5.1-HDMaN", true)
	is.Equal(info.Name, "21")
	is.Equal(info.Year, "2008")
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "Blu-ray")
	is.Equal(info.Codec, "H.264")
	is.Equal(info.Audio, "Dolby TrueHD 5.1")
	is.Equal(info.Producer, "HDMaN")
	is.Equal(info.MediaType, TypeMovie)

	info = Parse("Das Boot S04 WEB-DL 1080p H.264 DDP 5.1-WAYNE", false)
	is.Equal(info.Name, "Das Boot")
	is.Equal(info.Season, []int{4})
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "WEB-DL")
	is.Equal(info.Codec, "H.264")
	is.Equal(info.Audio, "DDP 5.1")
	is.Equal(info.Producer, "WAYNE")
	is.Equal(info.MediaType, TypeTVSeason)

	info = Parse("Das Boot S04 WEB-DL 1080p H.264 DDP 5.1-WAYNE", true)
	is.Equal(info.Name, "Das Boot")
	is.Equal(info.Season, []int{4})
	is.Equal(info.Resoluton, "1080p")
	is.Equal(info.Quality, "WEB-DL")
	is.Equal(info.Codec, "H.264")
	is.Equal(info.Audio, "Dolby Digital Plus 5.1")
	is.Equal(info.Producer, "WAYNE")
	is.Equal(info.MediaType, TypeTVSeason)
}
